# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: rsa-cert-4096
  namespace: default
spec:
  commonName: cluster.local
  dnsNames:
    - test.cluster.local
  duration: 2160h0m0s
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: nvidia-platform
  renewBefore: 360h0m0s
  secretName: rsa-cert-4096
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: "RSA"
    size: 4096